[[MiniZinc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "186f2585f35dcb63f792622522f8f91101cecb5d"
libc = "glibc"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "e0a5e45246523cf383f545ef48906be812eb1ee42f44483448db62b583d38c62"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.10.1+0/MiniZinc.v2.10.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MiniZinc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53e3723079c61cac65a45321c734b9ce186f2ea8"
libc = "musl"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "2e8eda35eca23e1a9c0408cdf2abf4579fc677008cde93f023e9fa3cf64134e3"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.10.1+0/MiniZinc.v2.10.1.aarch64-linux-musl-cxx11.tar.gz"
[[MiniZinc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39d800a6c6be9d5ad1b2534661930b9d980beed6"
libc = "glibc"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "44eeb5ee60f6c57084342497dda4be2485a63ef18876c940a77958b8bef82f07"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.10.1+0/MiniZinc.v2.10.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MiniZinc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ac7a3152ea2ecec71e2457ff0d41ca58659772b"
libc = "musl"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "1722589880bcf405b8e440a68e30134f50d4b525e5a10caf6b368e856a8c66bb"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.10.1+0/MiniZinc.v2.10.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MiniZinc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0aa8c8d92a3fa7bd50e7631392edcb3344496f6c"
libc = "glibc"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "2f59ac7449fc96c4c20431d99829365fb967d49f6c3dfb6b8e4807c0107b28b1"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.10.1+0/MiniZinc.v2.10.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MiniZinc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9d18a7720e463b1d5fd6b0975a6a4a8d0fe6e09"
libc = "musl"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "b49fb3d446b0f876fd64263ed304b23cfa044b1a707dfcaf5ea62083ed087628"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.10.1+0/MiniZinc.v2.10.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MiniZinc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b208412ccf57cc8f8b42208cc6cf8384962c0d5"
libc = "glibc"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "d29f78c65a9156df82f8e076c6b6621a3d12baa1013ce184cb1d4a0e7b4ccf7f"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.10.1+0/MiniZinc.v2.10.1.i686-linux-gnu-cxx11.tar.gz"
[[MiniZinc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b7f4e939fedc6f01ee28536884904e03e53bf48"
libc = "musl"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "9bd187940f8726892f018330252ebfae8bc43448b8f5432126f8f19eb7cfe1e9"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.10.1+0/MiniZinc.v2.10.1.i686-linux-musl-cxx11.tar.gz"
[[MiniZinc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24a013d05788793ece186d74a1e27d62dd63e752"
libc = "glibc"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "2b10f527652e3be592d2cb7416cd18b70987d50ef42f04302c8c7f26a9e6f1fb"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.10.1+0/MiniZinc.v2.10.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MiniZinc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2dcd103623059b81044ea2e6bc31dc7b555227f3"
libc = "glibc"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "eb7263f1b63ae9deff206d755b8bc7369f59d866b6d0f9fc5a36d8543e10984b"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.10.1+0/MiniZinc.v2.10.1.riscv64-linux-gnu-cxx11.tar.gz"
[[MiniZinc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5cd48ce4bfa3353af68ab74e5efecac3e6283a4"
libc = "glibc"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "25c9031edba0393c0c214181bb0fe0d145544d2300e07695aada906e666efdcb"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.10.1+0/MiniZinc.v2.10.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MiniZinc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4527c96e9ae4e64baa54ab32bec8a562ba91ca9e"
libc = "musl"
os = "linux"

    [[MiniZinc.download]]
    sha256 = "d6ab02747ccf2150c983fc168e7c416b9c55a27b743e7a469c4f7f25a9d0183d"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.10.1+0/MiniZinc.v2.10.1.x86_64-linux-musl-cxx11.tar.gz"
[[MiniZinc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cf1fab740258e89814f8c6ef92aac786d74a66b9"
os = "windows"

    [[MiniZinc.download]]
    sha256 = "64bfe57c15927ce5d3c1f581dd1b99b42371fa536d4b0b3ef1371046168a1afe"
    url = "https://github.com/JuliaBinaryWrappers/MiniZinc_jll.jl/releases/download/MiniZinc-v2.10.1+0/MiniZinc.v2.10.1.x86_64-w64-mingw32-cxx11.tar.gz"
